// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication22.Data;

namespace WebApplication22.Migrations
{
    [DbContext(typeof(GithubApiDBContext))]
    partial class GithubApiDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication22.Models.GithubRepository", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GithubUserDetailsUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HtmlUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WatchersCount")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("GithubUserDetailsUserId");

                    b.ToTable("GithubRepositories");
                });

            modelBuilder.Entity("WebApplication22.Models.GithubUserDetails", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("GithubUserDetails");
                });

            modelBuilder.Entity("WebApplication22.Models.GithubRepository", b =>
                {
                    b.HasOne("WebApplication22.Models.GithubUserDetails", null)
                        .WithMany("Repositories")
                        .HasForeignKey("GithubUserDetailsUserId");
                });

            modelBuilder.Entity("WebApplication22.Models.GithubUserDetails", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
